# openapi: 3.1.0
# info:
#   version: 1.0.0
#   title: Contacts app
#   license:
#     name: Apache 2.0
#     url: http://www.apache.org/licenses/LICENSE-2.0.html
#   description: This is a documentation of Contacts app
# tags:
#   - name: Contacts
#     description: Operations about contacts.
#   - name: Auth
#     description: Auth operations.
# servers:
#   - url: http://localhost:3000
#   - url: https://nodejs-hw-mongodb-4vnp.onrender.com
# paths:
#   /contacts:
#     get:
#     $ref: ../swagger/paths/contacts/get.yaml
#     post:
#     $ref: ../swagger/paths/contacts/post.yaml
#   /contacts/{contactId}:
#     delete:
#       $ref: ../swagger/paths/contacts/{id}/delete.yaml
#     patch:
#       $ref: ../swagger/paths/contacts/{id}/patch.yaml
#     get:
#       $ref: ../swagger/paths/contacts/{id}/get.yaml
#   /auth/login:
#     post:
#       $ref: ../swagger/paths/auth/login.yaml
#   /auth/refresh:
#     post:
#       $ref: ../swagger/paths/auth/refresh.yaml
#   /auth/logout:
#     post:
#       $ref: ../swagger/paths/auth/logout.yaml
#   /auth/send-reset-email:
#     post:
#       $ref: ../swagger/paths/auth/send-reset-email.yaml
#   /auth/reset-pwd:
#     post:
#       $ref: ../swagger/paths/auth/reset-pwd.yaml
#   /auth/get-oauth-url:
#     get:
#       $ref: ../swagger/paths/auth/get-oauth-url.yaml
#   /auth/confirm-oauth:
#     post:
#       $ref: ../swagger/paths/auth/confirm-oauth.yaml
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer

openapi: 3.1.0
info:
  version: 1.0.0
  title: Aqua API
  description: API documentation for the Contacts app, including user and authentication operations.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Users
    description: Operations for managing users.
  - name: Auth
    description: Operations related to user authentication and authorization.

servers:
  - url: http://127.0.0.1:8080
    description: Local development server
  - url: https://aqua-api-fkf8.onrender.com
    description: Production server

paths:
  /users/all:
    get:
      $ref: '../swagger/paths/users/get.yaml'
  /users/current:
    patch:
      $ref: '../swagger/paths/users/current/patch.yaml'
    get:
      $ref: '../swagger/paths/users/current/get.yaml'
  /auth/signup:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/signin:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /auth/get-oauth-url:
    get:
      $ref: '../swagger/paths/auth/get-oauth-url.yaml'
  /auth/confirm-oauth:
    post:
      $ref: '../swagger/paths/auth/confirm-oauth.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Use the Bearer token for authorization.
