openapi: 3.1.0
info:
  version: 1.0.0
  title: Aqua API
  description: API documentation for the Aqua track, including users and authentication operations.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Water
    description: Operations with water consumed by users and consumption analytics.
  - name: Users
    description: Operations for managing users.
  - name: Auth
    description: Operations related to user authentication and authorization.

servers:
  - url: https://aqua-api-fkf8.onrender.com
    description: Production server

paths:
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
  /water/day/{date}:
    get:
      $ref: ../swagger/paths/water/day/{date}/get.yaml
  /water/month/{month}:
    get:
      $ref: ../swagger/paths/water/month/{month}/get.yaml
  /users/current:
    patch:
      $ref: '../swagger/paths/users/current/patch.yaml'
    get:
      $ref: '../swagger/paths/users/current/get.yaml'
  /auth/signup:
    post:
      $ref: '../swagger/paths/auth/signup.yaml'
  /auth/signin:
    post:
      $ref: '../swagger/paths/auth/signin.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /auth/get-oauth-url:
    get:
      $ref: '../swagger/paths/auth/get-oauth-url.yaml'
  /auth/confirm-oauth:
    post:
      $ref: '../swagger/paths/auth/confirm-oauth.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Use the Bearer token for authorization.
